version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries:
  - en
  - technical
  - python
words:
  - covdefaults
  - FURB
  - Panaintescu
  - pypa
  - techdocs
ignoreWords: []
import: []
