version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries:
  - en
  - technical
  - python
words:
  - covdefaults
  - Craciun
  - FILECOVERAGE
  - FURB
  - junitxml
  - Panaintescu
  - posargs
  - pypa
  - techdocs
  - toxworkdir
  - XDIST
ignoreWords: []
import: []
