version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - FURB
  - Hasher
  - levelname
  - pyclass
  - pymethods
  - pymodule
  - pyyaml
  - sdist
  - tomlkit
ignoreWords: []
import: []
